### ISSUE TITLE
Setup: Image Overview

### ISSUE THREAD

**Issue by mariothomsen** [mariothomsen/keepit#11]
## Value Statement
As a ** user **,
I need ** an overview of the keepits **,
so that ** I've an overview **.

## Description (Text, Scribble, Wireframe, Design)
<img src="#"> 

## Acceptance Criteria
- [ ] Should show all tags the user have been saved
- [ ] Should show all images the user have been saved

## Tasks
- [ ] Setup FE 
- [ ] Setup BE new function in image controller for response all images and tags

## Complexity
medium
