### ISSUE TITLE
Filter on Image-Overview

### ISSUE THREAD

**Issue by mariothomsen** [mariothomsen/keepit#12]
## Value Statement
As a ** user **,
I need ** a way to filter the images **,
so that ** I can easily find them **.

## Description (Text, Scribble, Wireframe, Design)
<img src="#"> 

## Acceptance Criteria
- [ ] After a tag has been clicked, the image with this tag should be shown.
- [ ] The choosen tag should be marked as choosen
- [ ] If a user click again on a choosen tag, the filter should be reseted

## Tasks
- [ ] Setup dummy layout
- [ ] Setup OnClick for tags

## Complexity
medium
