### ISSUE TITLE
Tagging function on NewKeepitPage

### ISSUE THREAD

**Issue by mariothomsen** [mariothomsen/keepit#14]
## Value Statement
As a ** user **,
I need ** to tag my keepit **,
so that ** ... **.

## Description (Text, Scribble, Wireframe, Design)
<img src="#"> 

## Acceptance Criteria
- [ ] After a tag has been clicked, the tag should be marked as choosen.
- [ ] If a user click again on a choosen tag, the tag should be not marked as choosen anymore.

## Tasks
- [ ] Add status to tag-useState
- [ ] Implement click on function for tags 

## Complexity
small
