### ISSUE TITLE
Implement Vision API services

### ISSUE THREAD

**Issue by mariothomsen** [mariothomsen/keepit#4]
## Value Statement
As a ** user **,
I need ** to have category-suggestions **,
so that ** it's easier to save keepits **.

## Description (Text, Scribble, Wireframe, Design)
...
<img src="#"> 

## Acceptance Criteria
- [ ] descriptions

## Tasks
- [ ] Implement label-detections
- [ ] Implement text-detections
- [ ] Implement logo-detections

## Complexity
medium
